config/routes.rb
RealEstate::Application.routes.draw do
  resources :listings

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :city, :state, :name, :price, :for_sale, :for_rent
  validates_presence_of :city, :state, :name
  
  class << self
    def by_state(state)
      where(:state => state)
    end
    
    def by_city(city)
      where(:city => city)
    end
    
    def by_sale_type(sale_type)
      case sale_type
      when 'for_sale' then for_sale
      when 'for_rent' then for_rent
      else
        where(nil)
      end
    end
    
    def for_sale
      where(:for_sale => true)
    end
    
    def for_rent
      where(:for_rent => true)
    end
    
    def search(params)
      search = Listing.scoped
      search = search.by_city(params[:city]) if params[:city]
      search = search.by_state(params[:state]) if params[:state]
      search = search.by_sale_type(params[:sale_type]) if params[:sale_type]
      search
    end
    
    def available_states
      find_available(:state)
    end
    
    def available_cities
      find_available(:city)
    end
    
  private
    def find_available(column_name)
      Listing.group(column_name).select(column_name).collect(&column_name).sort
    end
  end
  
  def for_sale?
    for_sale
  end
  
  def for_rent?
    for_rent
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.search(params)
  end
  
  def show
    @listing = Listing.find(params[:id])
  end
  
  def new
    @listing = Listing.new
  end
  
  def create
    @listing = Listing.new(params[:listing])
    if @listing.save
      flash[:notice] = "Successfully created listing."
      redirect_to @listing
    else
      render :action => 'new'
    end
  end
  
  def edit
    @listing = Listing.find(params[:id])
  end
  
  def update
    @listing = Listing.find(params[:id])
    if @listing.update_attributes(params[:listing])
      flash[:notice] = "Successfully updated listing."
      redirect_to @listing
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    flash[:notice] = "Successfully destroyed listing."
    redirect_to listings_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/listings_helper.rb
module ListingsHelper

  def listings_title(params)
    type = case params[:sale_type]
      when 'for_sale' then "For Sale"
      when 'for_rent' then "For Rent"
      else "All Available"
    end
    
    base = "#{type} Listings"
    if params[:city] && params[:state].nil?
      base += " in #{params[:city]}"
    elsif params[:city] && params[:state]
      base += " in #{params[:city]}, #{params[:state]}"
    elsif params[:city].nil? && params[:state]
      base += " in #{params[:state]}"
    end
    base  
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper  
  
  def link_for_city(city)
    link_to city, listings_path(:city => city)
  end
  
  def link_for_city_with_state(city, state)
    link_to "#{city}, #{state}", listings_path(:city => city, :state => state)
  end
  
  def link_for_state(state)
    link_to state, listings_path(:state => state)
  end
end

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/listings/_listing.html.haml
.listing
  %h3= listing.name
  %h4
    = "[For Rent] " if listing.for_rent?
    = "[For Sale]" if listing.for_sale?
  %p= "Located in #{listing.city}, #{listing.state}"
  %p= raw "View all properties in #{link_for_city_with_state(listing.city, listing.state)} or #{link_for_state(listing.state)}"

app/views/listings/edit.html.erb
<% title "Edit Listing" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @listing %> |
  <%= link_to "View All", listings_path %>
</p>

app/views/listings/index.html.haml
- title "Listings"

.navigation
  %p Listings by State:
  %ul
    - Listing.available_states.each do |state|
      %li= link_to state, listings_path(:state => state)
  
  %p Listings by City
  %ul
    - Listing.available_cities.each do |city|
      %li= link_to city, listings_path(:city => city)
      
  %p Filter by Sale Type
  %ul
    %li= link_to "For Sale", listings_path(params.merge(:sale_type => 'for_sale'))
    %li= link_to "For Rent", listings_path(params.merge(:sale_type => 'for_rent'))
    %li= link_to "Either", listings_path(params.merge(:sale_type => 'any'))

%h2= listings_title(params)

%ul.actions
  %li= link_to "Create a New Listing", new_listing_path

= render :partial => 'listing', :collection => @listings

app/views/listings/new.html.erb
<% title "New Listing" %>

<%= render 'form' %>

<p><%= link_to "Back to List", listings_path %></p>

app/views/listings/show.html.erb
<% title "Listing" %>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>
<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>
<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <%= link_to "Edit", edit_listing_path(@listing) %> |
  <%= link_to "Destroy", @listing, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", listings_path %>
</p>